name: cicd

on:
  push:
   paths:
     - src/**
   branches:
     - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
      
      - 
        name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV
        
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tlepono/python-app:${{ env.SHORT_SHA }}
    outputs:
      commit_id : ${{ env.SHORT_SHA }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      #clone repo
      - uses: actions/checkout@v3

      -
        name: Modify Values File
        shell: bash
        run: |
         echo ${{needs.ci.outputs.commit_id}}
         pip install yq
         COMMIT_ID=${{needs.ci.outputs.commit_id}} \
         yq -Yi '.image.tag = strenv(COMMIT_ID)' charts/python-app/values.yaml
      -
        name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with "${{needs.ci.outputs.commit_id}}"'
      -
        name: Install ArgoCD
        shell: bash
        run: |
         curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
         sudo chmod +x argocd
         sudo mv ./argocd /usr/local/bin/argocd
      -
        name: ArgoCD App Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

